spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auction
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 12
          fetch_size: 12
        order_inserts: true
        order_updates: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  password-hash:
    salt-length: 16
    hash-length: 32
    parallelism: 1
    memory: 65536
    iterations: 3

  services:
    s3:
      endpoint: http://localhost:9000
      accessKey: user
      secretKey: password
      bucketName: projectbucket

  image:
    max-width-horizontal: 1080
    max-height-horizontal: 566
    max-size-square: 1080
    supported-image-types: "image/png,image/jpeg,image/jpg"
server:
  port: 8080