spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auction
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 12
          fetch_size: 12
        order_inserts: true
        order_updates: true

  data:
    redis:
      port: 6379
      host: localhost
      cache-size: 30
      lot-cache-entry-threshold-minutes: 3

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      replicationFactor: 1
      partitions: 1
      names:
        update-lot: updateLotTopic
        new-bid: newBidTopic
        delete-lot: deleteLotTopic
    consumer:
      group-id:
        lot-group: lot
        heater-group: heater

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    problemdetails:
      enabled: false

  jwt:
    secret: "V+X1dN5RxYQkPKF3UcC4d3+3fXwn1wFfJ+qg6Y7KzMo="
    expiration: 86400000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  password-hash:
    salt-length: 16
    hash-length: 32
    parallelism: 1
    memory: 65536
    iterations: 3

  services:
    s3:
      endpoint: http://localhost:9000
      accessKey: user
      secretKey: password
      bucketName: projectbucket
      duration-url: 7

  image:
    max-width-horizontal: 1080
    max-height-horizontal: 566
    max-size-square: 1080
    supported-image-types: "image/png,image/jpeg,image/jpg"
server:
  port: 8080